<a href="https://colab.research.google.com/github/chacha86/pythonai2/blob/main/%ED%8C%90%EB%8B%A4%EC%8A%A4_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
stu = pd.read_excel('/content/students.xlsx')

In [ ]:
stu

In [ ]:
# 위에서 5개 확인

stu.head()

In [ ]:
# 아래에서 5개 확인
stu.tail()

In [ ]:
# 요약 정보 보기
stu.info()

In [ ]:
# 통계 정보 보기
stu.describe()

In [ ]:
# 컬럼 목록 리스트로 가져오기

stu.columns.values

array(['번호', '이름', '국어', '영어', '수학', '지역명', '생년월일'], dtype=object)

In [ ]:
# 인덱스 목록 리스트로 가져오기
stu.index.values

In [ ]:
# 특정 컬럼 삭제
stu.drop('생년월일', axis=1)


# 특정 로우 삭제
stu.drop(4, axis=0)


# 특정 컬럼 여러개 삭제
stu.drop(['생년월일', '지역명'], axis=1)

In [ ]:
# 특정 컬럼 선택
stu['이름']
stu['수학']

# 특정 컬럼 여러개 선택
stu[['이름', '수학']]

stu[['국어', '영어', '수학']]

In [ ]:
# 특정 로우 선택(인덱스 값으로)
stu.loc[4]


# 특정 로우(인덱스 순서로)
stu.iloc[5]

# 특정 컬럼의 특정 로우 선택
stu.loc[4, '수학']
stu.loc[4, ['이름', '국어', '영어', '수학']]

stu.loc[[4, 6], ['이름', '국어', '영어']]

stu.loc[4:6, ['이름', '국어', '영어'] ]

In [ ]:
# boolean 접근

stu_5 = stu.head()

stu_5.loc[[0, 4]]

stu_5.loc[[True, False, False, False, True]]

stu_5.loc[[False, True, True, False, False]]

# 조건으로 로우 선택

idx = stu_5['수학'] < 80
stu_5.loc[idx]

stu_5.loc[stu_5['지역명'] == '대전']

   번호   이름  국어  영어  수학 지역명       생년월일
0   1  이현진  68  77  81  대전 2050-08-17
4   5  김혜수  83  76  67  대전 2050-01-25

In [ ]:
# 아래 문제를 해결해주세요.


# 1. 국어가 80점 이상인 학생의 이름과 생년월일
stu[stu['국어'] >= 80][['이름', '생년월일']]


# 2. 수학이 80점 미만인 학생의 영어와 국어 점수
stu.loc[stu['수학'] < 80][['영어', '국어']]


# 3. 국어와 수학이 90점 이상인 학생의 이름, 수학, 국어 점수
stu.loc[(stu['국어'] >= 90) & (stu['수학'] >= 90)]


# 4. 모든 과목이 60점 미만인 학생의 번호, 이름, 생년월일
stu.loc[(stu['국어'] < 60) & (stu['영어'] < 60) & (stu['수학'] < 60)][['번호', '이름', '생년월일']]

# 5. 대전 지역 학생들의 이름, 국어, 영어, 수학 점수
stu.loc[stu['지역명'] == '대전'][['이름','국어','영어', '수학']]

In [ ]:
# 정렬

# 오름차순
stu.sort_values('수학')

# 내림차순
stu.sort_values('수학', ascending=False)

# 복합 정렬
stu.sort_values(['수학', '국어'], ascending=[False, False])

In [ ]:
# 집계(그룹핑)
stu.groupby('지역명')['수학'].mean()
stu.groupby('지역명')['수학'].sum()
stu.groupby('지역명')['수학'].max()
stu.groupby('지역명')['수학'].min()

지역명
광주    63
대구    60
대전    60
부산    62
서울    60
울산    64
Name: 수학, dtype: int64

In [ ]:
# 아래 문제를 해결해주세요.


# 1. 학생들의 총점, 평균 구하기
stu[['국어', '영어', '수학']].mean(axis=1)
stu[['국어', '영어', '수학']].sum(axis=1)



# 2. 학생들의 평균이 높은 순으로 정렬. 만약 평균이 같다면 학번으로 오름차순
stu['평균'] = stu[['국어', '영어', '수학']].mean(axis=1)
# stu[['국어', '영어', '수학']].mean(axis=1).sort_values(ascending=False)

In [ ]:
stu.sort_values(['평균', '번호'], ascending=[False, True])

    번호   이름  국어  영어  수학 지역명       생년월일         평균
10  11  이민은  94  91  98  광주 2050-09-07  94.333333
67  68  이혜운  83  97  97  울산 2050-10-05  92.333333
81  82  정준동  82  95  99  울산 2050-04-07  92.000000
40  41  김명은  87  88  99  대전 2050-05-09  91.333333
56  57  정현연  79  97  98  부산 2050-05-11  91.333333
..  ..  ...  ..  ..  ..  ..        ...        ...
32  33  김지동  61  73  72  광주 2050-04-16  68.666667
66  67  정현운  70  71  63  광주 2050-03-27  68.000000
98  99  강준동  62  69  69  광주 2050-11-24  66.666667
45  46  정명동  60  62  73  광주 2050-06-03  65.000000
24  25  장철운  61  62  64  부산 2050-02-05  62.333333

[100 rows x 8 columns]